# Generated by Django 4.2.2 on 2023-09-17 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labanmanagement', '0003_rename_paritculars_expenditure_particulars_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenditure',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='expenditure',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
