# Generated by Django 4.2.2 on 2023-09-17 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labanmanagement', '0004_expenditure_time_alter_expenditure_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenditure',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='expenditure',
            name='time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
