# Generated by Django 4.2.2 on 2023-09-19 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labanmanagement', '0005_alter_expenditure_date_alter_expenditure_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenditure',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='expenditure',
            name='time',
            field=models.TimeField(),
        ),
    ]
