# Generated by Django 4.2.2 on 2023-09-19 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labanmanagement', '0006_alter_expenditure_date_alter_expenditure_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='handlecustomer',
            old_name='laag_account',
            new_name='account',
        ),
    ]
