# Generated by Django 4.2.5 on 2023-10-01 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labanmanagement', '0007_rename_laag_account_handlecustomer_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('order_time', models.TimeField()),
                ('name_of_client', models.CharField(max_length=100)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('occasion', models.CharField(max_length=100)),
                ('rate', models.DecimalField(decimal_places=2, default=60, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=3, max_digits=100)),
                ('date_of_delivery', models.DateField()),
                ('payment', models.CharField(choices=[('Advanced', 'Advanced'), ('After delivery', 'After delivery'), ('Not paid', 'Not paid')], max_length=30)),
                ('paid', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('balance', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=100, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('remarks', models.TextField(max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='handlecustomer',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payasyougocustomer',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='payasyougocustomer',
            name='qty',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payasyougocustomer',
            name='rate',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=100),
            preserve_default=False,
        ),
    ]
