# Generated by Django 4.2.5 on 2023-10-01 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labanmanagement', '0008_bulkorder_alter_handlecustomer_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkorder',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bulkorder',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='qty',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='customer',
            name='rate',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='handlecustomer',
            name='qty',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='handlecustomer',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=3, default=60, max_digits=100, null=True),
        ),
    ]
