# Generated by Django 4.1.2 on 2023-10-13 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labanmanagement', '0009_bulkorder_delivered_alter_bulkorder_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calf',
            name='breed',
            field=models.CharField(choices=[('HF', 'Holstein Friesian (HF)'), ('HF Jersey (cross)', 'HF Jersey (cross)'), ('Jersey', 'Jersey'), ('Guernsey', 'Guernsey'), ('Ayrshire', 'Ayrshire'), ('Brown Swiss', 'Brown Swiss'), ('Milking Shorthorn', 'Milking Shorthorn'), ('Dutch Belted', 'Dutch Belted'), ('Red and White Holstein', 'Red and White Holstein'), ('Friesian', 'Friesian'), ('Montbéliarde', 'Montbéliarde'), ('Normande', 'Normande'), ('Swedish Red', 'Swedish Red'), ('Danish Red', 'Danish Red'), ('Ayshire', 'Ayshire'), ('Canadienne', 'Canadienne'), ('Shorthorn', 'Shorthorn'), ('Simmental', 'Simmental'), ('Gelbvieh', 'Gelbvieh'), ('Fleckvieh', 'Fleckvieh'), ('Norwegian Red', 'Norwegian Red'), ('Finnish Ayrshire', 'Finnish Ayrshire'), ('South Devon', 'South Devon'), ('Holstein-Sahiwal', 'Holstein-Sahiwal'), ('Meuse-Rhine-Issel', 'Meuse-Rhine-Issel'), ('British Friesian', 'British Friesian'), ('Kostroma', 'Kostroma'), ('Kholmogory', 'Kholmogory'), ('Red Poll', 'Red Poll'), ('Murray Grey', 'Murray Grey'), ('Chianina', 'Chianina'), ('Charolais', 'Charolais'), ('Simbrah', 'Simbrah')], max_length=100),
        ),
        migrations.AlterField(
            model_name='cow',
            name='breed',
            field=models.CharField(choices=[('HF', 'Holstein Friesian (HF)'), ('HF Jersey (cross)', 'HF Jersey (cross)'), ('Jersey', 'Jersey'), ('Guernsey', 'Guernsey'), ('Ayrshire', 'Ayrshire'), ('Brown Swiss', 'Brown Swiss'), ('Milking Shorthorn', 'Milking Shorthorn'), ('Dutch Belted', 'Dutch Belted'), ('Red and White Holstein', 'Red and White Holstein'), ('Friesian', 'Friesian'), ('Montbéliarde', 'Montbéliarde'), ('Normande', 'Normande'), ('Swedish Red', 'Swedish Red'), ('Danish Red', 'Danish Red'), ('Ayshire', 'Ayshire'), ('Canadienne', 'Canadienne'), ('Shorthorn', 'Shorthorn'), ('Simmental', 'Simmental'), ('Gelbvieh', 'Gelbvieh'), ('Fleckvieh', 'Fleckvieh'), ('Norwegian Red', 'Norwegian Red'), ('Finnish Ayrshire', 'Finnish Ayrshire'), ('South Devon', 'South Devon'), ('Holstein-Sahiwal', 'Holstein-Sahiwal'), ('Meuse-Rhine-Issel', 'Meuse-Rhine-Issel'), ('British Friesian', 'British Friesian'), ('Kostroma', 'Kostroma'), ('Kholmogory', 'Kholmogory'), ('Red Poll', 'Red Poll'), ('Murray Grey', 'Murray Grey'), ('Chianina', 'Chianina'), ('Charolais', 'Charolais'), ('Simbrah', 'Simbrah')], max_length=30),
        ),
    ]
