# Generated by Django 4.2.5 on 2023-10-14 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labanmanagement', '0011_calf_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='birthevent',
            old_name='mother',
            new_name='dam',
        ),
        migrations.RemoveField(
            model_name='calf',
            name='mother',
        ),
        migrations.AddField(
            model_name='calf',
            name='dam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calves_as_dam', to='labanmanagement.cow'),
        ),
    ]
