# Generated by Django 4.1.2 on 2023-10-19 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labanmanagement', '0012_rename_mother_birthevent_dam_remove_calf_mother_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birthevent',
            name='calf_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
