# Generated by Django 4.2.5 on 2023-10-19 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labanmanagement', '0013_alter_birthevent_calf_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkorder',
            name='delivery_time',
            field=models.CharField(blank=True, choices=[('Morning', 'M'), ('Evening', 'E')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='handlecustomer',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='handlecustomer',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=100, null=True),
        ),
    ]
