# Generated by Django 4.2.7 on 2023-11-05 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labanmanagement', '0014_bulkorder_delivery_time_alter_handlecustomer_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payasyougocustomer',
            name='payment_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
